name: container-env-ts-template
description: Template to create a container environment.
types:
  - env-template
inputs:
  - label: "Application name (e.g. my-awesome-app):"
    type: text
    name: project_name
  - label: "Application version (e.g. 1.0.0):"
    type: text
    name: project_version
  - label: "Internet facing:"
    type: bool
    name: internet_facing
  - label: "Existing VPC:"
    type: bool
    name: container_has_vpc
  - label: "Default VPC:"
    type: bool
    name: vpc_default
    condition:
      variable: "container_has_vpc"
      operator: "=="
      value: true
  - label: "VPC id (e.g. vpc-xxxxxxxxxxxxxxxxx):"
    type: text
    name: container_vpc_id
    condition:
      variable: "container_has_vpc"
      operator: "=="
      value: true
    condition:
      variable: "vpc_default"
      operator: "=="
      value: false
  - label: "VPC region:"
    type: text
    name: vpc_region
    default: us-east-1
    condition:
      variable: "container_has_vpc"
      operator: "=="
      value: true
  - label: "VPC CIDR (e.g. 10.0.0.0/16):"
    type: text
    name: container_vpc_cidr
    condition:
      variable: "container_has_vpc"
      operator: "=="
      value: false
  - label: "VPC maximum number of AZs:"
    type: int
    name: vpc_max_azs
    default: 99
    condition:
      variable: "container_has_vpc"
      operator: "=="
      value: false
  - label: "VPC name:"
    type: text
    name: vpc_name
    condition:
      variable: "container_has_vpc"
      operator: "=="
      value: false
  - label: "Subnet type:"
    type: text
    name: container_subnet_type
    items:
    - PRIVATE_ISOLATED
    - PRIVATE_WITH_NAT
    - PUBLIC
    default: PUBLIC
  - label: "Subnet ids (e.g. subnet-xxxxxxxxxxxxxxxxx,subnet-xxxxxxxxxxxxxxxxx):"
    type: text
    name: container_subnet_ids
    condition:
      variable: "container_has_vpc"
      operator: "=="
      value: true
  - label: "Ingress IPv4 sources (e.g. 10.0.0.0/16,10.1.0.0/16):"
    type: text
    name: container_ingress_ipv4_sources
  - label: "CloudWatch Container Insights:"
    type: bool
    name: container_insights
  - label: "Sample app:"
    type: bool
    name: sample_app
computedInputs:
  app_class_name: "{{ inputs.project_name|replace('_', '-')|replace(' ', '-')|title|replace('-', '') }}"
  project_name: "{{ inputs.project_name|replace('_', '-')|replace(' ', '-')|lower }}"
